@username = menta

### register
POST {{base_url}}/brawlers/register
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "P@ssw0rd",
    "display_name": "{{username}}"
}


### login
# @name login
POST {{base_url}}/authentication/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "P@ssw0rd"
}

### Get access token from login response
@access_token = {{login.response.body.access_token}}